const PROFILE_CATALOG = {
  balanced: {
    id: "balanced",
    label: "Balanced",
    description: "Combined-arms posture that pressures VP hexes while avoiding reckless exposure.",
    aggression: 0.56,
    defenseBias: 0.52,
    vpFocus: 1.0,
    reserveRatio: 0.24,
    acceptableForceRatio: 0.95,
    dangerTolerance: 0.48,
    threatPenalty: 0.9,
    supportBias: 0.9,
    artilleryBias: 1.0,
    reconBias: 0.95,
    routeRiskBias: 0.72,
    fallbackBias: 0.55,
    urbanBias: 0.0,
    roughTerrainBias: 0.0,
    openTerrainBias: 0.0,
    scarceAssetConservation: 0.7,
    objectivePersistence: 0.62,
    terrainPreferences: {
      urban: 0.08,
      rough: 0.08,
      forest: 0.06,
      open: 0.0,
      wet: -0.2,
      mountain: -0.15,
      bridge: 0.2,
    },
  },
  aggressive_breakthrough: {
    id: "aggressive_breakthrough",
    label: "Aggressive Breakthrough",
    description: "Masses combat power against a main effort and commits reserves early if a seam appears.",
    aggression: 0.84,
    defenseBias: 0.28,
    vpFocus: 1.15,
    reserveRatio: 0.14,
    acceptableForceRatio: 0.78,
    dangerTolerance: 0.78,
    threatPenalty: 0.52,
    supportBias: 1.05,
    artilleryBias: 1.1,
    reconBias: 0.9,
    routeRiskBias: 1.2,
    fallbackBias: 0.18,
    urbanBias: -0.05,
    roughTerrainBias: -0.12,
    openTerrainBias: 0.12,
    scarceAssetConservation: 0.45,
    objectivePersistence: 0.82,
    terrainPreferences: {
      urban: -0.04,
      rough: -0.08,
      forest: -0.04,
      open: 0.12,
      wet: -0.28,
      mountain: -0.32,
      bridge: 0.26,
    },
  },
  cautious_defender: {
    id: "cautious_defender",
    label: "Cautious Defender",
    description: "Preserves combat power, prioritizes mutual support, and prefers strong defensive terrain.",
    aggression: 0.28,
    defenseBias: 0.88,
    vpFocus: 0.95,
    reserveRatio: 0.34,
    acceptableForceRatio: 1.22,
    dangerTolerance: 0.22,
    threatPenalty: 1.18,
    supportBias: 1.08,
    artilleryBias: 0.96,
    reconBias: 0.9,
    routeRiskBias: 0.5,
    fallbackBias: 0.94,
    urbanBias: 0.08,
    roughTerrainBias: 0.18,
    openTerrainBias: -0.1,
    scarceAssetConservation: 0.92,
    objectivePersistence: 0.45,
    terrainPreferences: {
      urban: 0.12,
      rough: 0.18,
      forest: 0.16,
      open: -0.14,
      wet: -0.12,
      mountain: 0.02,
      bridge: 0.08,
    },
  },
  rough_terrain_flanker: {
    id: "rough_terrain_flanker",
    label: "Rough Terrain Flanker",
    description: "Prefers concealment, broken terrain, and alternate axes that avoid the obvious main road.",
    aggression: 0.62,
    defenseBias: 0.44,
    vpFocus: 1.02,
    reserveRatio: 0.22,
    acceptableForceRatio: 0.88,
    dangerTolerance: 0.58,
    threatPenalty: 0.76,
    supportBias: 0.92,
    artilleryBias: 0.92,
    reconBias: 1.1,
    routeRiskBias: 0.84,
    fallbackBias: 0.48,
    urbanBias: -0.06,
    roughTerrainBias: 0.3,
    openTerrainBias: -0.18,
    scarceAssetConservation: 0.68,
    objectivePersistence: 0.68,
    terrainPreferences: {
      urban: -0.04,
      rough: 0.28,
      forest: 0.22,
      open: -0.18,
      wet: -0.08,
      mountain: 0.1,
      bridge: 0.1,
    },
  },
  urban_grinder: {
    id: "urban_grinder",
    label: "Urban Grinder",
    description: "Methodically closes on towns and built-up hexes, using artillery and mutual support to wear defenders down.",
    aggression: 0.6,
    defenseBias: 0.56,
    vpFocus: 1.08,
    reserveRatio: 0.2,
    acceptableForceRatio: 1.02,
    dangerTolerance: 0.46,
    threatPenalty: 0.84,
    supportBias: 1.06,
    artilleryBias: 1.18,
    reconBias: 0.86,
    routeRiskBias: 0.64,
    fallbackBias: 0.42,
    urbanBias: 0.34,
    roughTerrainBias: 0.08,
    openTerrainBias: -0.08,
    scarceAssetConservation: 0.74,
    objectivePersistence: 0.7,
    terrainPreferences: {
      urban: 0.34,
      rough: 0.08,
      forest: 0.02,
      open: -0.1,
      wet: -0.22,
      mountain: -0.14,
      bridge: 0.14,
    },
  },
};

const THINK_BUDGETS = {
  fast: {
    id: "fast",
    label: "Fast",
    maxHypotheses: 2,
    planVariants: 1,
    lookaheadDepth: 0,
    candidateBreadth: 2,
  },
  standard: {
    id: "standard",
    label: "Standard",
    maxHypotheses: 3,
    planVariants: 1,
    lookaheadDepth: 0,
    candidateBreadth: 3,
  },
  deliberate: {
    id: "deliberate",
    label: "Deliberate",
    maxHypotheses: 3,
    planVariants: 2,
    lookaheadDepth: 2,
    candidateBreadth: 4,
  },
};

export function getAiProfile(profileId = "balanced") {
  return PROFILE_CATALOG[profileId] || PROFILE_CATALOG.balanced;
}

export function listAiProfiles() {
  return Object.values(PROFILE_CATALOG);
}

export function getThinkBudgetConfig(thinkBudget = "standard") {
  return THINK_BUDGETS[thinkBudget] || THINK_BUDGETS.standard;
}

export function listThinkBudgets() {
  return Object.values(THINK_BUDGETS);
}

export function terrainPreferenceForCategory(profile, category) {
  return profile?.terrainPreferences?.[category] || 0;
}
